version: '3'
services:
  mongo-service:
    image: "mongo:4.2.8"
    ports:
      - "27017:27017"
  redis:
    image: redis:4.0.9
    volumes:
      - ./tmp/redis:/data
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo-service
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/
  sidekiq:
    depends_on:
      - mongo-service
      - redis
    build: .
    command: sidekiq -q default
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379/